---
abstract: 'Strip superfluous spaces from pesky files.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Munge-Whitespace
provides:
  Dist::Zilla::Plugin::Munge::Whitespace:
    file: lib/Dist/Zilla/Plugin/Munge/Whitespace.pm
    version: '0.001002'
recommends:
  Moose: '2.000'
requires:
  Dist::Zilla::Role::FileMunger: '1.000'
  Moose: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Dist-Zilla-Plugin-Munge-Whitespace/issues
  homepage: https://github.com/kentnl/Dist-Zilla-Plugin-Munge-Whitespace
  repository: https://github.com/kentnl/Dist-Zilla-Plugin-Munge-Whitespace.git
version: '0.001002'
